### PR TITLE
Brace typo in doc/0_introduction.md

### PR DESCRIPTION
**Pull request by Kubo2**
This change is [Reviewable](https://reviewable.io/reviews/google/recki-ct/10)

### CODE REVIEW

**Comment by ircmaxell** [comment]
@Kubo2 Did you sign the CLA? See https://github.com/google/recki-ct/blob/master/CONTRIBUTING.md 

Once you have, I can merge this. 

Thanks!!!

**Comment by Kubo2** [comment]
@ircmaxell Oh, sorry, I missed that. It means that if I have @gmail.com email address and an account from Google, I have signed CLA — did I understand it correctly? Or do I have to do also something else?  (It is only two characters, feel free to merge it, if you agree with the change.)

**Comment by ircmaxell** [comment]
No, that's for Google employees (I'll clean up the wording). 

I can't merge unless the CLA is signed, so...

**Comment by Kubo2** [comment]
@ircmaxell I have signed the CLA. How do I share it with you?

**Pull request closed without merging**
